apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Chart.Name }}
